# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-vscode
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and DOTNET_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: CI-CD

env:
  AZURE_RG: RG3
  AZURE-LOCATION: WestEurope
  AZURE-WEBAPP-NAME: suuu-mywebapp

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-job:
    runs-on: ubuntu-latest
    env:
      configuration: release

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.configuration }}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration}}
    - name: Publish
      run: dotnet publish --configuration ${{ env.configuration }} --output ${{runner.temp}}/publish
    - name: Upload the Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish_artifact
        path: ${{ runner.temp }}/publish
        retention-days: 30
    - name: Upload template
      uses: actions/upload-artifact@v4
      with:
        name: templates_artifact
        path: ./templates/*
        retention-days: 30
  RG-Job:
    runs-on: ubuntu-latest
    needs: [build-job]
    steps:
      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: create resource group
        uses: Azure/cli@v2
        with:
          inlineScript:
            az group create --name ${{env.AZURE_RG }} --location ${{ env.AZURE-LOCATION }}
  Webapp-Job:
    runs-on: ubuntu-latest
    needs: [RG-Job]
    steps:
      - name: Download templates
        uses: actions/download-artifact@v4
        with:
          name: templates_artifact
          path: ${{runner.temp }}/templates
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: deploy BICEP
        uses: azure/arm-deploy@v2
        id: deploywebapp
        with:
          deploymentName: create-webapp
          subscriptionId: ${{secrets.AZURE_SUBSCRIPTION}}
          resourceGroupName: ${{env.AZURE_RG }}
          template: ${{runner.temp}}/templates/webapp.bicep
          parameters: location=${{env.AZURE-LOCATION}} appName=${{env.AZURE-WEBAPP-NAME}}
      - name: Download publish
        uses: actions/download-artifact@v4
        with:
          name: publish_artifact
          path: ${{runner.temp}}/publish
      - name: Azure Webapp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{steps.deploywebapp.outputs.webappname }}
          package: ${{runner.temp}}/publish
